name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "thameem022@gmail.com"
          git config --global user.name "Thameem022"
          git remote add hf https://$HF_TOKEN@huggingface.co/spaces/Thameem022/mlops-cs-1
          git push --force hf main

